# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 11 Aug 2020 12:36:38 +0000
*               @ALL          1
*               @user         8
