<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: octocat
 * Date: Wed, 12 Aug 2020 10:27:23 +0000
 */

$conf['title'] = '민복국 세계관 위키';
$conf['start'] = '대문';
$conf['lang'] = 'ko';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
