<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Tue, 11 Aug 2020 12:36:38 +0000
 */
$conf['title'] = '민복국 세계관 위키';
$conf['lang'] = 'ko';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
