# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 11 Aug 2020 12:36:38 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

octocat:$2y$10$cL9jHHfnQkqKOAy7X6Tsvenk86GaBLtgMsF5HQpZSTfOkvcojuC3m:배선우:schcat_msw@naver.com:admin,user
